version: '3'
# this can be then plugged to a larger yml while where you want all the services to work in a swarm
# here we are just making a file for a single service to run
services:
  srvauth:
    build: /home/pi/eensymachines-in/srvauth
    stop_grace_period: 2s
    volumes:
      - "/home/pi/go/bin/:/home/pi/go/bin/"
      - "/var/local/srvauth:/var/local/srvauth"
      - "/sys:/sys" # for the go code to access it, we would need the acess to sys
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
    environment:
      - LOGF=/var/local/srvauth/device.log
      - BASEURL=http://localhost:8080/
      - HALTSOCK=/var/local/srvauth/halt.sock
    tty: true
    stdin_open: true
    container_name: srvauth
    # command: ["tail", "-f", "/dev/null"]
    command: ["/home/pi/eensymachines-in/srvauth/srvauth","-flog=false", "-verbose=true"]