version: '3'
# this can be then plugged to a larger yml while where you want all the services to work in a swarm
# here we are just making a file for a single service to run
services:
  srvauth:
    build: ${REPODIR}/srvauth
    volumes:
      - ${GOBINDIR}:${GOBINDIR}
      - /sys:/sys
      - ${TIMEZ}:${TIMEZ}
      - ${LCLTM}:${LCLTM}
      - ${LCLDIR}:${LCLDIR}
      - ${SOCKSDIR}:${SOCKSDIR}
    environment:
      - LOGF=${LCLDIR}/logs/srvauth.log
      - AUTHBASEURL=${AUTHBASEURL}
      - REGBASEURL=${REGBASEURL}
      - HALTSOCK=${SOCKSDIR}/halt.sock
      - USER=${OWNER}
      - RLYS=${RELAYS}
    tty: ${TTYSTDIN}
    stdin_open: ${TTYSTDIN}
    container_name: srvauth
    # command: ["tail", "-f", "/dev/null"]
    command: ["${REPODIR}/srvauth/srvauth","-flog=${FLOG}", "-verbose=${VERBOSE}"]